src/components/Menu/GlobalSettings/TransactionSettings.bmp.tsx, src/views/Swap/index.bmp.tsx
=> fix icon display

package.json, src/app.bmp.tsx, yarn.lock
=> feat(swap): Update sentry version

src/components/Loader/CircleLoader.bmp.tsx, src/components/Logo/CurrencyLogo.tsx
=> fix(swap): Fix loading circle and logo radius

src/components/SearchModal/ImportRow.bmp.tsx
=> fix(Swap): Import Row style

src/components/Logo/CurrencyLogo.tsx
=> fix(swap): Fix logo radius

package.json, src/app.bmp.tsx
=> fix(Swap): Bmp get env

package.json, src/app.config.ts, src/components/Menu/GlobalSettings/SettingsModal.tsx, src/state/user/reducer.bmp.ts, src/theme.json, src/views/Swap/index.bmp.tsx
=> feat(Swap): Update dark mode

bmp.config/adaptor/redux-persist-storage.js, bmp.config/index.js, src/Providers.bmp.tsx
=> feat(Swap): Support mp storage

src/state/index.bmp.ts
=> fix(Swap): Read isDark from app when mp open

src/hooks/useEagerConnect.bmp.ts, src/hooks/useSwapCallback.bmp.ts
=> feat(Swap): Add error capture

src/contexts/Localization/helpers.bmp.ts
=> feat(Swap): Support i18n

src/state/index.bmp.ts
=> feat(Swap): Add throttle to redux

src/components/SearchModal/CurrencyList.bmp.tsx
=> Virtual list

src/components/Menu/GlobalSettings/SettingsModal.bmp.tsx, src/components/SearchModal/CurrencyList.bmp.tsx
=> feat(Swap): Use scroll-view

src/components/Menu/GlobalSettings/SettingsModal.bmp.tsx, src/components/QuestionHelper/index.bmp.tsx
=> feat(Swap): Update question help style

src/PageProvider.bmp.tsx, src/components/Toast/Toast.bmp.tsx, src/components/Toast/ToastContainer.bmp.tsx
=> fix(Swap): Toast not work problem

src/components/Loader/CircleLoader.bmp.tsx, src/views/Swap/bmp/index.tsx
=> fix(Swap): Same dom id problem

src/components/Loader/Dots.bmp.tsx
=> feat(liquidity): Support dot component

src/views/Swap/bmp/index.tsx
Reverts kim-pink-ba/pancake-frontend#33
=> Revert "3 14"

src/views/Swap/bmp/index.tsx
=> fix(Swap): Icon

src/views/PoolFinder/index.bmp.tsx
=> feat(Liquidity): Find page work

src/components/App/AppHeader.bmp.tsx, src/views/AddLiquidity/bmp/index.tsx, src/views/PoolFinder/index.bmp.tsx
=> feat(Liquidity): AppHeader style

package.json, src/components/SearchModal/CurrencyList.bmp.tsx, src/components/SearchModal/CurrencySearch.tsx, src/components/SearchModal/CurrencySearchModal.bmp.tsx, src/views/AddLiquidity/bmp/index.tsx, src/views/PoolFinder/index.bmp.tsx, yarn.lock
=> feat(CurrencySearchModal): Refactor to FloatLayout

src/components/SearchModal/CurrencySearchModal.bmp.tsx
=> feat(Liquidity): Border radius

src/components/FloatLayout/index.bmp.tsx, src/components/SearchModal/CurrencyList.bmp.tsx, src/components/SearchModal/CurrencySearchModal.bmp.tsx, src/components/TransactionConfirmationModal/index.bmp.tsx
=> feat(Liquidity): Float layoutto Transaction

src/components/FloatLayout/index.bmp.tsx, src/components/SearchModal/CurrencySearchModal.bmp.tsx, src/components/TransactionConfirmationModal/index.bmp.tsx, src/views/AddLiquidity/ConfirmAddModalBottom.tsx
=> fix(Liquidity): Remove hash after transaction

src/components/FloatLayout/index.bmp.tsx, src/components/TransactionConfirmationModal/index.bmp.tsx, src/views/AddLiquidity/bmp/index.tsx, src/views/RemoveLiquidity/index.bmp.tsx
=> feat(Liquidity): Show ErrorMessage

src/views/Swap/bmp/index.tsx
=> fix(swap): Fix Page not found

src/views/AddLiquidity/bmp/index.tsx, src/views/Pool/index.bmp.tsx, src/views/PoolFinder/index.bmp.tsx, src/views/RemoveLiquidity/index.bmp.tsx
=> feat(Liquidity): Errorboundary for Liquidity

src/components/Select/Select.bmp.tsx, src/pages/farms/history.bmp.tsx, src/pages/farms/index.bmp.tsx, src/state/index.bmp.ts, src/views/BmpHome/components/farmsWrapper.bmp.tsx, src/views/BmpHome/context/farmsContext.bmp.tsx, src/views/BmpHome/index.tsx, src/views/Farms/Farms.bmp.tsx, src/views/Farms/components/DepositModal.bmp.tsx, src/views/Farms/components/FarmCard/ApyButton.bmp.tsx, src/views/Farms/components/FarmCard/CardHeading.bmp.tsx, src/views/Farms/components/FarmTabButtons/index.bmp.tsx, src/views/Farms/components/FarmTable/Earned.bmp.tsx
=> feat(Farms): Init Farms Page

src/components/Select/Select.bmp.tsx
=> feat(Farms): Add Select Component

src/components/Select/Select.bmp.tsx, src/views/Farms/Farms.bmp.tsx, src/views/Farms/components/FarmCard/FarmCard.bmp.tsx, src/views/Farms/components/FarmTable/CellLayout.bmp.tsx, src/views/Farms/components/FarmTable/Farm.bmp.tsx, src/views/Farms/components/FarmTable/FarmTable.bmp.tsx, src/views/Farms/components/FarmTable/Liquidity.bmp.tsx, src/views/Farms/components/FarmTable/Multiplier.bmp.tsx, src/views/Farms/components/FarmTable/Row.bmp.tsx
=> feat(Farms): WIP Farms Table

src/views/BmpHome/index.tsx, src/views/Farms/components/FarmTable/Actions/StakedAction.bmp.tsx
=> feat(Farms): Remove useRouter

src/views/Farms/components/FarmTable/Actions/StakedAction.bmp.tsx
=> fix(Farms): Remove div

src/components/QuestionHelper/index.bmp.tsx, src/components/bmp/Tooltip.tsx
=> feat(farm): Add Tooltip

src/views/BmpHome/constants.ts, src/views/BmpHome/context/farmsContext.bmp.tsx, src/views/BmpHome/index.tsx, src/views/Farms/components/FarmCard/DetailsSection.bmp.tsx, src/views/Farms/components/FarmCard/FarmCard.bmp.tsx, src/views/Farms/components/FarmTable/Actions/ActionPanel.bmp.tsx, src/views/Farms/components/FarmTable/FarmTable.bmp.tsx
=> feat(Farms): Add Farms to AddLiquidity

project.config.json, src/PageProvider.bmp.tsx, src/components/QuestionHelper/index.bmp.tsx, src/contexts/bmp/TooltipContext/Provider.tsx, src/contexts/bmp/TooltipContext/Tooltip.tsx, src/contexts/bmp/TooltipContext/index.ts, src/views/Farms/components/FarmTable/Multiplier.bmp.tsx
=> feat(farm): Upgrade useTooltip with context

src/components/Balance.bmp.tsx, src/views/BmpHome/index.tsx, src/views/Farms/Farms.bmp.tsx, src/views/Farms/components/DepositModal.bmp.tsx, src/views/Farms/components/FarmCard/StakeAction.bmp.tsx, src/views/Farms/components/FarmTable/Actions/HarvestAction.bmp.tsx, src/views/Farms/components/FarmTable/Actions/StakedAction.bmp.tsx
=> fix(Farms): Go to Add in DepositModal

src/state/index.bmp.ts, src/views/BmpHome/index.tsx
=> feat(farm): Remove farm temporarily

src/components/Menu/GlobalSettings/index.bmp.tsx
=> fix(globalSetting): Remove id

src/PageProvider.bmp.tsx, src/components/SearchModal/CurrencyList.bmp.tsx, src/components/SearchModal/CurrencySearch.bmp.tsx
=> fix(SearchModal): Reduce VirtualList size

src/app.config.ts, src/theme.json
=> feat(mpConfig): Change tabBar color

src/views/Pool/index.bmp.tsx
Reverts kim-pink-ba/pancake-frontend#63
=> Revert "feat(liquidity): Optmize perf when page in background"

src/views/Pool/index.bmp.tsx
=> feat(pool): Fix perf issue when siwtch tab

src/views/Pool/index.bmp.tsx
=> fix(pool): Fix change liquidity pool visible error

src/views/Pool/index.bmp.tsx
=> fix(Liquidity): Use origin data

src/custom-tab-bar/index.scss, src/custom-tab-bar/index.tsx
=> fix(tabbar): Fix tabbar style issue

bmp.config/adaptor/ethers-web/src.ts/geturl.ts
=> feat(ethers): Increase timeout

src/custom-tab-bar/index.tsx
=> feat(tabbar): Support i18n

src/views/AddLiquidity/bmp/index.tsx, src/views/RemoveLiquidity/index.bmp.tsx
=> feat(liquidity): Add LP in modal title

src/views/AddLiquidity/bmp/index.tsx
=> fix(add): Fix title error

src/views/Pool/index.bmp.tsx
=> feat(Liquidity): Navigate to academy

.env.production
=> feat(liquidity): Replace RPC url

src/components/TokenImage/index.bmp.tsx, src/views/Farms/components/FarmCard/CardHeading.bmp.tsx, src/views/Farms/components/FarmTable/Farm.bmp.tsx
=> fix(farm): Fix pair icon

src/pages/farms/history.bmp.tsx, src/pages/farms/index.bmp.tsx, src/views/Farms/Farms.bmp.tsx
=> feat(Farms): Reduce meaningless rerender

src/components/Modal/ModalInput.bmp.tsx, src/components/Select/Select.bmp.tsx, src/views/Farms/components/DepositModal.bmp.tsx
=> fix(Farms): DepositModal && Select

src/views/Farms/components/WithdrawModal.bmp.tsx
=> fix(Farms): WithdrawModal input

project.config.json, src/hooks/useSwapCallback.bmp.ts, src/views/Swap/bmp/index.tsx
=> feat(swap): Update track to collect volume

src/views/AddLiquidity/index.tsx, src/views/RemoveLiquidity/index.bmp.tsx
=> feat(liquidity): Add track

src/views/Swap/bmp/index.tsx
=> fix(swap): Fix missed swap click track

src/components/SearchModal/CurrencyList.bmp.tsx, src/views/bmp/BmpPage/components/VirtualList/FixedSizeList.js, src/views/bmp/BmpPage/components/VirtualList/VariableSizeList.js, src/views/bmp/BmpPage/components/VirtualList/createListComponent.js, src/views/bmp/BmpPage/components/VirtualList/domHelpers.js, src/views/bmp/BmpPage/components/VirtualList/index.js, src/views/bmp/BmpPage/components/VirtualList/memoize.js, src/views/bmp/BmpPage/components/VirtualList/timer.js
=> feat(VirtualList): Support VariableSizeList

src/custom-tab-bar/index.scss
=> fix(tabbar): Fix wrong font-family

src/app.bmp.tsx, src/contexts/AnalyticsContext.tsx, src/hooks/useSwapCallback.bmp.ts, src/utils/bmp/getEnv.ts
=> feat(track): Only track when prod

src/views/AddLiquidity/bmp/index.tsx, src/views/AddLiquidity/index.tsx
=> fix(addLiquidity): Fix addLiquidity track error

src/pages/farms/index.bmp.tsx, src/views/Farms/Farms.bmp.tsx, src/views/Farms/components/FarmCard/FarmCard.bmp.tsx, src/views/bmp/BmpPage/components/VirtualList/VariableSizeList.js, src/views/bmp/BmpPage/index.tsx
=> feat(Farms): Switch CardMode to VirtualList

src/views/bmp/liquidity/index.tsx
=> feat(liquidity): Add screen track

src/views/Farms/Farms.bmp.tsx, src/views/Farms/components/FarmTable/FarmTable.bmp.tsx, src/views/Farms/components/FarmTable/Row.bmp.tsx
=> feat(Farms): VirtualList for FarmTable

src/components/RoiCalculatorModal/index.bmp.tsx
=> fix(RoiCalculator): Default symbol

src/pages/farms/index.bmp.tsx, src/views/Farms/components/FarmTable/FarmTable.bmp.tsx
=> fix(Farms): Sync expand

src/app.bmp.tsx, src/components/ExpandableSectionButton/ExpandableSectionButton.bmp.tsx, src/components/SearchInput/SearchInput.bmp.tsx, src/custom-tab-bar/index.tsx, src/pages/farms/index.bmp.tsx, src/polyfill.bmp.ts, src/views/Farms/Farms.bmp.tsx, src/views/Farms/components/DepositModal.bmp.tsx, src/views/Farms/components/FarmTable/FarmTable.bmp.tsx, src/views/Farms/components/FarmTable/Row.bmp.tsx, src/views/Farms/components/WithdrawModal.bmp.tsx
=> fix(Farms): Lots of bug

src/components/ExpandableSectionButton/ExpandableSectionButton.bmp.tsx
=> fix(Farms): ExpandableSectionButton

src/views/Farms/components/FarmTable/Farm.bmp.tsx
=> fix(farm): Fix tokenPair size [17]

src/config/constants/farms.ts
=> fix: Update farm list

src/views/RemoveLiquidity/index.bmp.tsx
=> fix: Fix liquidity 0 button [38]

src/PageProvider.bmp.tsx, src/pages/farms/index.bmp.tsx, src/views/Farms/Farms.bmp.tsx
=> fix(PollBlock): Always render pollBlock hooks

src/config/constants/farms.ts
=> feat: Update farm config

src/app.bmp.tsx, src/polyfill.bmp.ts, src/utils/apr.bmp.ts
=> feat(Farms): Use other cdn to get apr

src/pages/farms/index.bmp.tsx, src/views/Farms/components/FarmCard/FarmCard.bmp.tsx, src/views/Farms/components/FarmTable/FarmTable.bmp.tsx, src/views/Swap/styles.bmp.tsx
=> fix(Farms): Wrong padding

src/hooks/useDisclaimer.bmp.tsx
=> feat: Update disclaimer #39

src/views/Farms/Farms.bmp.tsx, src/views/bmp/BmpPage/index.tsx
=> feat(Farms): Add Header

src/views/Farms/Farms.bmp.tsx
=> fix(Farms): Header

src/pages/farms/index.bmp.tsx, src/views/Farms/components/FarmTable/FarmTable.bmp.tsx
=> fix(Farms): OOM

src/components/App/AppHeader.bmp.tsx, src/components/App/Transactions/index.bmp.tsx
=> fix: Fix liquidity icon #43

src/components/RoiCalculatorModal/RoiCalculatorFooter.bmp.tsx, src/components/RoiCalculatorModal/index.bmp.tsx, src/views/bmp/BmpPage/components/customNav.bmp.tsx
=> fix: Fix ui bugs with ROICalculator #50

src/views/bmp/BmpPage/components/VirtualList/createListComponent.js
=> feat(VirtualList): Remove memorize in virtuallist

src/views/Farms/hooks/useHarvestFarm.bmp.ts, src/views/Farms/hooks/useStakeFarms.bmp.ts
=> feat: Add farm track

src/views/Farms/hooks/useHarvestFarm.bmp.ts, src/views/Farms/hooks/useStakeFarms.bmp.ts
=> fix(farms): Replace tx to tx.hash

src/components/SearchModal/CurrencyList.bmp.tsx, src/pages/farms/index.bmp.tsx, src/views/Farms/components/FarmTable/FarmTable.bmp.tsx, src/views/bmp/BmpPage/components/VirtualList/createListComponent.js
=> fix(Farms): Memory leak

src/components/SearchModal/CurrencyList.bmp.tsx, src/pages/farms/index.bmp.tsx, src/views/Farms/components/FarmTable/FarmTable.bmp.tsx, src/views/bmp/BmpPage/components/VirtualList/createListComponent.js
- fix(Farms): Memory leak
- fix(Farms): Memory leak 2
=> chore: sync main branch

src/state/index.bmp.ts, src/state/pools/fetchPools.ts, src/state/pools/fetchPoolsUser.ts, src/state/pools/fetchVaultPublic.ts, src/state/pools/fetchVaultUser.ts, src/state/pools/helpers.ts, src/state/pools/hooks.ts, src/state/pools/index.ts, src/state/pools/selectors.ts
=> feat(pools): Update state

src/components/ToggleView/ToggleView.tsx
=> feat: Add toggleView

src/config/constants/pools.tsx
=> chore: Sync develop

bmp.config/adaptor/react-countup/index.tsx, bmp.config/index.js
=> feat: Add countup for taro

src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.bmp.tsx, src/views/Pools/components/PoolStatsInfo.tsx
=> feat: Support view token info

src/components/RoiCalculatorModal/RoiCalculatorFooter.bmp.tsx, src/components/RoiCalculatorModal/index.bmp.tsx, src/components/RoiCalculatorModal/useRoiCalculatorReducer.ts, src/utils/bmp/jump.ts, src/views/Pools/components/CakeVaultCard/VaultStakeModal.bmp.tsx
=> feat: Update RoiCalculatorModal

src/views/Pools/components/CakeVaultCard/VaultStakeModal.bmp.tsx
=> fix: Fix click roi icon

src/components/RoiCalculatorModal/index.bmp.tsx
=> feat: RoiModal style

src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.bmp.tsx, src/views/Pools/components/PoolStatsInfo.bmp.tsx
=> feat: Remove view-token-info

src/utils/bmp/jump.ts, src/views/bmp/farms/farmsContext.tsx
=> chore: Move jumpToLiquidity to jump.ts

src/views/Pools/components/CakeVaultCard/VaultStakeModal.bmp.tsx, src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
=> feat: Add track for pools

src/config/constants/bmp/track.ts, src/hooks/bmp/useHandleTrack.ts, src/hooks/useSwapCallback.bmp.ts, src/views/AddLiquidity/bmp/index.tsx, src/views/Farms/hooks/useHarvestFarm.bmp.ts, src/views/Farms/hooks/useStakeFarms.bmp.ts, src/views/Pools/components/CakeVaultCard/VaultStakeModal.bmp.tsx, src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx, src/views/RemoveLiquidity/index.bmp.tsx, src/views/Swap/bmp/index.tsx
=> chore: Isolate event track handles

src/hooks/useDisclaimer.bmp.tsx
=> feat: Move button into scrollView for useDisclaimer

src/hooks/useEagerConnect.bmp.ts
=> feat: Add wallet connected toast

src/contexts/bmp/TooltipContext/Tooltip.tsx
=> fix: Fix tooltip text color #6

src/views/Pools/components/LockedPool/Common/LockDurationField.bmp.tsx
=> fix: Fix RoiCalculatorModal change week error

src/components/RoiCalculatorModal/RoiCard.bmp.tsx
=> fix: Fix input collapse when click in Android #22

src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx, src/views/bmp/BmpPage/index.tsx
=> fix: Overlay can scroll background

src/hooks/useEagerConnect.bmp.ts
=> fix: Fix wallet notification without address

src/hooks/bmp/useHandleTrack.ts
=> fix: Fix can't track data

src/config/localization/mp-translations/en.json, src/hooks/useSwapCallback.bmp.ts, src/views/Pools/components/CakeVaultCard/index.bmp.tsx, src/views/Pools/components/PoolCard/Modals/StakeModal.bmp.tsx
=> fix(pools): Add track && error message
